import { ProfesorProfile } from "../../components/ProfesorProfile";
import photoIleanuBogdan from "../../assets/Poze Profesori/Bogdan Ileanu.jpg";
export function IleanuBogdanPage() {
  const data = {
    name: "ILEANU Bogdan",
    initials: "IB",
    photo: photoIleanuBogdan,
    role: "Conferențiar Universitar Dr.",
    specializations: [
      "Analiză statistică și econometrică",
      "Analiza datelor în domeniul sănătății publice",
      "Inegalități regionale și dezvoltare regională",
      "Reziliență economică și dezvoltare sustenabilă",
      "Capital intelectual și indicatori socio-economici",
      "Analiza relațiilor dintre educație, guvernanță și performanță economică",
    ],
    email: "bogdan.ileanu@csie.ase.ro",
    birou: "",
    facultate: "Facultatea de Cibernetică, Statistică și Informatică Economică",
    activitateDidactica: [],
    domeniiCercetare: [
      "Econometria Mediului și a Digitalizării - modelarea impactului noilor tehnologii asupra sustenabilității",
      "Modelarea efectelor de mediere în relații economice complexe",
      "Analiza cantitativă a antreprenoriatului verde",
      "Determinarea indicatorilor de sustenabilitate prin metode statistice",
      "Microeconometria Pieței Muncii și Socială - utilizarea modelelor econometrice pentru comportamentul individual și dinamica ocupării",
      "Modele de regresie pentru analiza preferințelor individuale",
      "Analiza statistică a competențelor și a decalajelor digitale",
      "Econometria sănătății și a sărăciei",
      "Econometria Seriilor de Timp și Analiză Sectorială - modele avansate pentru date pe termen lung",
      "Estimarea relațiilor pe termen lung prin modele ARDL (Autoregressive Distributed Lag)",
      "Analiza statistică a competitivității sectoriale și a șomajului",
      "Analiza seriilor de timp în context de criză",
      "Statistica Socială și Demografie Aplicată - modelarea fenomenelor demografice și a atitudinilor populației",
      "Analiza cantitativă a rezilienței la crize de sănătate",
      "Studiul statistic al atitudinilor populației",
    ],
    tezeDoctorat: [],
    publicatiiRelevante: [
      "Ileanu, B.V., Pană, A. (2024), From 2008–2011 Great Recession to COVID-19 pandemic: an analysis of resilience metrics in European regions, Empirica.",
      "Munteanu, I., Ileanu, B.V., Florea, I.O., Aivaz, K.A. (2024), Corruption perceptions in the Schengen Zone and their relation to education, economic performance, and governance, PLOS ONE.",
      "Popa, C. et al., Ileanu, B.V. (2023), Specific Septic Complications after Rectal Cancer Surgery: A Critical Multicentre Study, Cancers.",
      "Pantea-Stoian, A. et al., Ileanu, B.V. (2020), Death by SARS-CoV-2: a Romanian COVID-19 multi-centre comorbidity study, Scientific Reports.",
      "Dimian, G.C., Aceleanu, M., Ileanu, B.V., Serban, M. (2018), Unemployment and sectoral competitiveness in Southern European Union countries, Journal of Business Economics and Management.",
      "Boja, C.E., Herteliu, C., Dardala, M., Ileanu, B.V. (2018), Day of the week submission effect for accepted papers, Scientometrics.",
      "Dimian, G.C., Maftei, M., Jablonský, J. et al. (2025). The Influence of Digitalization on Greenhouse Gas Emissions in the European Union. The Analysis of the Mediating Effect of Renewable Energy Consumption. J Knowl Econ. WOS (în curs de indexare)",
      "Apostu S.A., Dimian G.C., Vasilescu M.D. (2024). An in-depth analysis of the relation of health and poverty in Europe. Panoeconomicus OnLine-First. WOS:001187378900005",
      "Dimian, G.C., Gheorghe, M., Boldeanu, D.M., Maftei, M. (2023). How digitalization, work-family balance, and work efficiency can influence employees' preferences for teleworking. Inzinerine. Ekonomika., 34(2), 139-157. WOS:000993994500002",
      "Vasilescu, M.D., Dimian, G.C., Gradinaru, G.I. (2022). Green entrepreneurship in challenging times: a quantitative approach for European countries. Economic Research-Ekonomska Istrazivanja. WOS:000823616800001",
      "Dimian, G.C., Vasilescu, M.D. et al. (2021). Analysis of the Europeans' attitudes towards vaccination in the context of the Covid-19 Pandemic. Ekonomický časopis 69(10), 997-1016. WOS:00074686550000",
      "Goschin, Z. and Dimian, G.C. (2021). Healthcare under pressure: modelling COVID-19 fatalities with multiscale geographically weighted regressions. Kybernetes. WOS:000703267700001",
      "Dimian, G.C., Apostu, S.A., Vasilescu, M.D., Aceleanu, M.I., Jablonsky, J. (2021). Vulnerability and resilience in health crises. Evidence from European countries. Technological and Economic Development of Economy, 27(4), 783-810. WOS:000681057300001",
      "Vasilescu M.D., Serban A.C., Dimian G.C., Aceleanu M.I., Picatoste X. (2020). Digital divide, skills and perceptions on digitalisation in the European Union. PLoS ONE 15(4): e0232032. WOS:000533192100001",
      "Dimian G.C., Marin E., Jablonsky J. (2019). Investigating the long and short-run salary-employment relationship in Romania: A sectorial approach using the ARDL model. Economic Computation and Economic Cybernetics Studies and Research, 53(1). WOS:000461762700001",
      "Dimian G.C., Aceleanu, M., Ileanu, B., Șerban, A. (2018). Unemployment and sectoral competitiveness in Southern European Union countries. Journal of Business Economics and Management, 19(3), 474-499. WOS:000453041400003",
      "Aceleanu, M., Șerban, A., Pociovălișteanu, D., Dimian G.C. (2017). Renewable energy: A way for a sustainable development in Romania. Energy Sources, Part B, 12(11), 958-963. WOS:000417485400003",
      "Dimian G.C., Begu, L., Jablonsky, J. (2017). Unemployment and labour market mismatch in the European Union Countries. Proceedings of Rijeka Faculty of Economics, 35(1), 13-44. WOS:000406769600001",
      "Dimian G.C., Ileanu, B., Aceleanu, M. (2016). Aging and economic competitiveness in the core of 'North Euro-zone'. Inzinerine Ekonomika-Engineering Economics Journal, 27(3), 253–263. WOS:000388489400002",
      "Dimian G.C., Ileanu, B., Jablonsky, J., Fabry, J. (2013). Analysis of European labour market in the crisis context. Prague Economic Papers, 1/2013, 50-71. WOS:000317807200003",
      "Mitruț, C., Constantin, L., Dimian G.C. (Bănică), Dimian, M. (2007). Indicators and methods for characterising regional specialization and concentration. Economic computation and economic cybernetics studies and research, 41(3-4), 5-13. WOS:000258575700001",
      "Bănică G.C., Constantin L., Profiroiu A., Dimian M. (2007). Regional convergence from the perspective of factor mobility and technological change. Economic Computation and Economic Cybernetics Studies and Research, 41(1-2), 167-177.",
      "Proiect postdoctoral POSDRU/89/1.5/S/59184 – Competențe pentru dezvoltarea durabilă a României (director proiect)",
      "Proiecte CNCSIS – AT, AC",
      "Proiecte CEEX și PNCDI II",
      "Proiecte privind competitivitatea regională, piața muncii, capitalul uman și politici de coeziune",
    ],
    proiecteCercetare: [
      "Advancing ground-breaking research in regional growth and development theories through a resilience approach: towards a convergent, balanced and sustainable European Union – proiect finanțat de UEFISCDI, membru (2019–2021).",
  "Understanding and modelling time-space patterns of psychology-related inequalities and polarization – proiect finanțat de UEFISCDI, membru (2018–2021).",
  "Integrative Mechanisms for Addressing Spatial Justice and Territorial Inequalities in Europe (IMAJINE) – proiect Horizon 2020, membru (2017–2019).",
  "Dezvoltarea de instrumente statistice și econometrice pentru măsurarea nivelului și impactului corupției asupra dezvoltării sectoriale și regionale – proiect finanțat de UEFISCDI, membru (2009–2011).",
  "Economia convențiilor, rețele sociale informale și reforma sistemului de pensii private și asigurări de viață – proiect finanțat de UEFISCDI, membru (2010–2011).",
  "Influența religiei asupra proceselor sociale din România – o abordare cantitativă utilizând tehnici de sondaj statistic – proiect finanțat de UEFISCDI, membru (2008–2011)."
],
    cvProfiluri: [
      {
        tip: "Google Scholar",
        url: "https://scholar.google.com/citations?user=gORUf2oAAAAJ&hl=ro&oi=ao",
      },
      {
        tip: "ResearchGate",
        url: "https://orcid.org/0000-0002-9229-3431",
      },
      { tip: "WOS", url: "https://www.webofscience.com/wos/author/record/V-1290-2019" },
    ],
  };

  return <ProfesorProfile data={data} />;
}
